In [1]:
# Imports
import csv
import json
import pandas as pd
import sys, getopt, pprint
import pymongo
from pymongo import MongoClient

In [2]:
# Set mongoDB connection as variable
conn = 'mongodb://localhost:27017'

# Pass connection to the pymongo instance.
client = pymongo.MongoClient(conn)

# Connect to a database. Will create one if not already available and creates a schema called etlProject.
db = client.etlProject

In [3]:
# Read CSVs into pdDBs
dataCoinbase = pd.read_csv('./data/coinbaseUSD_1-min_data_2014-12-01_to_2019-01-09.csv',encoding = 'ISO-8859-1')
dataBitstamp = pd.read_csv('./data/bitstampUSD_1-min_data_2012-01-01_to_2019-08-12.csv',encoding = 'ISO-8859-1')

# Add column to both pdDBs called 'exchange' and populate with respective exchange name.
dataCoinbase['exchange'] = 'coinbase'
dataBitstamp['exchange'] = 'bitstamp'

In [4]:
# Drop NaN lines from dataBitstamp
dataBitstamp.dropna(inplace=True)
dataBitstamp

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,exchange
0,1325317920,4.39,4.39,4.39,4.39,0.455581,2.000000,4.390000,bitstamp
478,1325346600,4.39,4.39,4.39,4.39,48.000000,210.720000,4.390000,bitstamp
547,1325350740,4.50,4.57,4.50,4.57,37.862297,171.380338,4.526411,bitstamp
548,1325350800,4.58,4.58,4.58,4.58,9.000000,41.220000,4.580000,bitstamp
1224,1325391360,4.58,4.58,4.58,4.58,1.502000,6.879160,4.580000,bitstamp
...,...,...,...,...,...,...,...,...,...
3997692,1565567760,11555.57,11555.57,11540.37,11540.58,0.036868,425.909106,11552.336234,bitstamp
3997693,1565567820,11553.49,11556.22,11553.49,11556.22,0.623462,7204.428272,11555.520505,bitstamp
3997694,1565567880,11559.73,11561.22,11546.77,11561.22,0.159070,1838.731403,11559.252199,bitstamp
3997695,1565567940,11559.73,11589.73,11528.73,11528.73,16.198210,187504.635170,11575.638889,bitstamp
3997696,1565568000,11527.44,11551.57,11520.00,11520.00,23.805939,274731.256920,11540.450291,bitstamp

In [5]:
# Drop NaN lines from dataCoinbase
dataCoinbase.dropna(inplace=True)
dataCoinbase

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,exchange
0,1417411980,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000,coinbase
7,1417412400,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000,coinbase
51,1417415040,370.00,370.00,370.00,370.00,0.010000,3.700000,370.000000,coinbase
77,1417416600,370.00,370.00,370.00,370.00,0.026556,9.825550,370.000000,coinbase
1436,1417498140,377.00,377.00,377.00,377.00,0.010000,3.770000,377.000000,coinbase
...,...,...,...,...,...,...,...,...,...
2099755,1546898520,4006.01,4006.57,4006.00,4006.01,3.382954,13553.433078,4006.390309,coinbase
2099756,1546898580,4006.01,4006.57,4006.00,4006.01,0.902164,3614.083169,4006.017233,coinbase
2099757,1546898640,4006.01,4006.01,4006.00,4006.01,1.192123,4775.647308,4006.003635,coinbase
2099758,1546898700,4006.01,4006.01,4005.50,4005.50,2.699700,10814.241898,4005.719991,coinbase
2099759,1546898760,4005.51,4006.01,4005.51,4005.99,1.752778,7021.183546,4005.745614,coinbase

In [6]:
# Create btc_df of combined data from dataBitstamp and dataCoinbase.
btc_df = dataCoinbase.append(dataBitstamp, ignore_index=True)
btc_df

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,exchange
0,1417411980,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000,coinbase
1,1417412400,300.00,300.00,300.00,300.00,0.010000,3.000000,300.000000,coinbase
2,1417415040,370.00,370.00,370.00,370.00,0.010000,3.700000,370.000000,coinbase
3,1417416600,370.00,370.00,370.00,370.00,0.026556,9.825550,370.000000,coinbase
4,1417498140,377.00,377.00,377.00,377.00,0.010000,3.770000,377.000000,coinbase
...,...,...,...,...,...,...,...,...,...
4756505,1565567760,11555.57,11555.57,11540.37,11540.58,0.036868,425.909106,11552.336234,bitstamp
4756506,1565567820,11553.49,11556.22,11553.49,11556.22,0.623462,7204.428272,11555.520505,bitstamp
4756507,1565567880,11559.73,11561.22,11546.77,11561.22,0.159070,1838.731403,11559.252199,bitstamp
4756508,1565567940,11559.73,11589.73,11528.73,11528.73,16.198210,187504.635170,11575.638889,bitstamp
4756509,1565568000,11527.44,11551.57,11520.00,11520.00,23.805939,274731.256920,11540.450291,bitstamp

In [7]:
# Create table called 'btc_db'
btc_table = db.BTC
btc_table

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'etlProject'), 'BTC')

In [8]:
# Convert df to JSON object that is mongoDB friendly.
payload = json.loads(btc_df.to_json(orient='records'))

# Clearing table to prevent duplication of data.
btc_table.delete_many({})

# Inserting the JSON object into mongoDB
btc_table.insert_many(payload)

# Print row count of new mongoDB 'btc_table' to confirm it matches row count of df 'btc_df'
print(btc_table.count_documents({}))

4756510

In [9]:
# Declare variable that gets all the records, then sorts them by the '_id' in descending order.
returnedData = db.BTC.find().sort('_id', -1)

# Print first ten records of returnedData from mongoDB.
for i in range(10):
    print(returnedData[i])

{'_id': ObjectId('5ea4575f45bdffc4d4f4032c'), 'Timestamp': 1565568000, 'Open': 11527.44, 'High': 11551.57, 'Low': 11520.0, 'Close': 11520.0, 'Volume_(BTC)': 23.80593911, 'Volume_(Currency)': 274731.25692, 'Weighted_Price': 11540.450291, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f4032b'), 'Timestamp': 1565567940, 'Open': 11559.73, 'High': 11589.73, 'Low': 11528.73, 'Close': 11528.73, 'Volume_(BTC)': 16.19821048, 'Volume_(Currency)': 187504.63517, 'Weighted_Price': 11575.638889, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f4032a'), 'Timestamp': 1565567880, 'Open': 11559.73, 'High': 11561.22, 'Low': 11546.77, 'Close': 11561.22, 'Volume_(BTC)': 0.1590701, 'Volume_(Currency)': 1838.7314033, 'Weighted_Price': 11559.252199, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40329'), 'Timestamp': 1565567820, 'Open': 11553.49, 'High': 11556.22, 'Low': 11553.49, 'Close': 11556.22, 'Volume_(BTC)': 0.62346203, 'Volume_(Currency)': 7204.4282718, 'Weighted_Price': 11555.520505, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40328'), 'Timestamp': 1565567760, 'Open': 11555.57, 'High': 11555.57, 'Low': 11540.37, 'Close': 11540.58, 'Volume_(BTC)': 0.03686779, 'Volume_(Currency)': 425.90910627, 'Weighted_Price': 11552.336234, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40327'), 'Timestamp': 1565567700, 'Open': 11537.63, 'High': 11551.63, 'Low': 11537.63, 'Close': 11551.63, 'Volume_(BTC)': 0.07405247, 'Volume_(Currency)': 855.34794007, 'Weighted_Price': 11550.565971, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40326'), 'Timestamp': 1565567640, 'Open': 11556.97, 'High': 11556.97, 'Low': 11535.42, 'Close': 11536.12, 'Volume_(BTC)': 5.93622567, 'Volume_(Currency)': 68594.445972, 'Weighted_Price': 11555.228825, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40325'), 'Timestamp': 1565567580, 'Open': 11549.34, 'High': 11549.74, 'Low': 11540.02, 'Close': 11549.74, 'Volume_(BTC)': 0.10305454, 'Volume_(Currency)': 1189.7756677, 'Weighted_Price': 11545.106772, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40324'), 'Timestamp': 1565567520, 'Open': 11547.31, 'High': 11558.24, 'Low': 11547.31, 'Close': 11558.24, 'Volume_(BTC)': 2.09243889, 'Volume_(Currency)': 24184.122669, 'Weighted_Price': 11557.863307, 'exchange': 'bitstamp'}
{'_id': ObjectId('5ea4575f45bdffc4d4f40323'), 'Timestamp': 1565567460, 'Open': 11545.51, 'High': 11551.97, 'Low': 11540.09, 'Close': 11551.97, 'Volume_(BTC)': 0.06042724, 'Volume_(Currency)': 697.56508691, 'Weighted_Price': 11543.884627, 'exchange': 'bitstamp'}